version: "3.9"
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: "always"
    command: redis-server --requirepass YOUR_PASS --appendonly yes    
    volumes:
      - "./redis/data:/data"
    environment: 
      - TZ=Europe/Berlin

  api:
    build:
      context: .
    ports:
      - 5001:5003
    command: ["python", "entrypoint.py"]  # use entrypoint.sh for production  
    restart: "always"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=YOUR_PASS
      - INFRARED_URL=http://ait-mock-api:5555/
      - INFRARED_USERNAME=test
      - INFRARED_PASSWORD=test
      - CITY_PYO=YOUR_CITY_PYO_URL
      - CLIENT_ID=YOUR_ID
      - CLIENT_PASSWORD=YOUR_PASSWORD

  worker:
    build:
      context: .
    restart: "always"
    command: celery -A tasks worker --loglevel=info
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=YOUR_PASS
      - INFRARED_URL=http://ait-mock-api:5555/
      - INFRARED_USERNAME=test
      - INFRARED_PASSWORD=test
      - CITY_PYO=YOUR_CITY_PYO_URL

  # run your own ait-mock-api for fast local debugging        
  ait-mock-api:
    build:
      context: .
    ports:
      - 5555:5000
    restart: "always"
    command: python wind/mock-api/mock_ait_api.py
