version: "3.9"
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: "always"
    command: redis-server --requirepass G0rDkQtRcl!E --appendonly yes
    volumes:
      - "./redis/data:/data"
    environment: 
      - TZ=Europe/Berlin

  api:
    build:
      context: .
    ports:
      - 5004:5000
    restart: "always"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=G0rDkQtRcl!E
      - INFRARED_URL=http://ait-mock-api:5555/
      - INFRARED_USERNAME=test
      - INFRARED_PASSWORD=test
      - CITY_PYO=https://api.hcu-dev.de/citypyo/

  worker:
    build:
      context: .
    restart: "always"
    command: celery -A tasks worker --loglevel=info
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=G0rDkQtRcl!E
      - INFRARED_URL=http://ait-mock-api:5555/
      - INFRARED_USERNAME=test
      - INFRARED_PASSWORD=test
      - CITY_PYO=https://api.hcu-dev.de/citypyo/

  # run your own ait-mock-api for fast local debugging        
  ait-mock-api:
    build:
      context: .
    ports:
      - 5555:5000
    restart: "always"
    command: python wind/mock-api/mock_ait_api.py
